### PR TITLE
Add bright colors

### LINKED ISSUE #12: Bright colors?
Is there any way to do the ["bright" colors](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit) specified by codes 90-97 (foreground) and 100-107 (background)?

### PR DESCRIPTION
**Pull request by dbeckwith**
Fixes #12

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Hmm, looks like the CI broke somehow. Well, good as time as ever to migrate the repo over to GitHub actions. Should be able to handle this within the next 24 hours or so.

**Comment by SergioBenitez** [comment]
Can we make `bright()` a style modifier? Or are there only certain colors that can be bright?

**Comment by dbeckwith** [comment]
Yeah I don't think it would make sense as a modifier since only the basic colors have bright versions. The name is maybe a little misleading, it's really just another type of color.

**Comment by ralpha** [comment]
I guess this PR fell into the void? Would be cool to have merged at some point.

**Comment by dbeckwith** [comment]
I think this is just waiting on @SergioBenitez to fix CI and approve.

**Comment by its-danny** [comment]
can this get merged? 🥺

**Comment by koushiro** [comment]
@SergioBenitez I have migrated the CI from travis to GitHub Actions, see #39 for details.

**Comment by SergioBenitez** [comment]
1.0.0-rc supports bright colors!

**Pull request closed without merging**
