### PR TITLE
Remove the `docify!` macro.

### PR DESCRIPTION
**Pull request by nnethercote**
This reduces the compile time for a non-incremental `cargo check` build
by about 60%. It also reduces the amount of code and is easier to read
because it uses standard Rust macros (`concat` and `stringify`) rather
than a DSL.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Awesome.

Can you compile the docs with and without this change and run a diff on the resulting files to ensure we generate the same docs?

**Comment by nnethercote** [comment]
Here is the diff when running `cargo expand` on the two versions: [change.txt](https://github.com/SergioBenitez/yansi/files/8328469/change.txt)
There are only minor whitespace changes.

I also ran `cargo doc` and looked at the generated documentation for the changed methods. The rendering in Firefox is identical except that the new version avoids an unnecessary space after `self` in the text on functions like `Style::bold` and `Style::is_bold`.

Before:
before

After:
after

**Comment by nnethercote** [comment]
Oh, I just realized that the leading space in all those string literals isn't necessary. I just pushed an update that removes them. Here's an updated `cargo expand` diff:  [change2.txt](https://github.com/SergioBenitez/yansi/files/8328518/change2.txt)

The rendered docs look identical to the previous version.

**Comment by SergioBenitez** [comment]
Merged in 0dd0178409fa199a36795f859927acc99b556113. Thanks again! :)

**Comment by nnethercote** [comment]
Thank you, and congratulations on the release of 0.5.1! :rocket:

**Pull request closed without merging**
